project_id = "xrtsioacrybmcexyhaia"

[functions.generate-protocol]
verify_jwt = false

[functions.create-student]
verify_jwt = false

[functions.analyze-movement]
verify_jwt = false

[functions.get-signed-url]
verify_jwt = false