// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/env.ts
function serverEnv(name) {
  const proc = globalThis.process;
  return proc?.env?.[name];
}
function requireServerEnv(name) {
  const v = serverEnv(name);
  if (!v) throw new Error(`Missing required env var: ${name}`);
  return v;
}

// src/lib/mcp/tools/whoami.ts
function supabaseForUser(ctx) {
  return createClient(requireServerEnv("SUPABASE_URL"), requireServerEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id, email, profile name and role (professional or student).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [profile, roleRow] = await Promise.all([
      supabase.from("profiles").select("id, full_name, email").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId).maybeSingle()
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail(),
      full_name: profile.data?.full_name ?? null,
      role: roleRow.data?.role ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-students.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(requireServerEnv("SUPABASE_URL"), requireServerEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_students_default = defineTool2({
  name: "list_students",
  title: "List students",
  description: "List students (patients) associated with the signed-in professional. Returns id, full_name and email.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data: links, error: linksError } = await supabase.from("professional_students").select("student_id").eq("professional_id", ctx.getUserId()).limit(limit ?? 50);
    if (linksError) {
      return { content: [{ type: "text", text: linksError.message }], isError: true };
    }
    const ids = (links ?? []).map((r) => r.student_id);
    if (ids.length === 0) {
      return {
        content: [{ type: "text", text: "No students found." }],
        structuredContent: { students: [] }
      };
    }
    const { data: profiles, error: profilesError } = await supabase.from("profiles").select("id, full_name, email").in("id", ids);
    if (profilesError) {
      return { content: [{ type: "text", text: profilesError.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(profiles, null, 2) }],
      structuredContent: { students: profiles ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-assessments.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(requireServerEnv("SUPABASE_URL"), requireServerEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_assessments_default = defineTool3({
  name: "list_assessments",
  title: "List assessments",
  description: "List functional assessments visible to the signed-in user. Optionally filter by student_id and status.",
  inputSchema: {
    student_id: z2.string().uuid().optional().describe("Filter by student profile id."),
    status: z2.enum(["not_started", "in_progress", "completed"]).optional().describe("Filter by assessment status."),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ student_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let q = supabase.from("assessments").select("id, student_id, professional_id, status, started_at, completed_at, notes, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (student_id) q = q.eq("student_id", student_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { assessments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-assessment.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(requireServerEnv("SUPABASE_URL"), requireServerEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_assessment_default = defineTool4({
  name: "get_assessment",
  title: "Get assessment details",
  description: "Fetch a functional assessment with its global test results, segmental test results, and findings.",
  inputSchema: {
    assessment_id: z3.string().uuid().describe("Assessment id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ assessment_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const [assessment, globals, segmentals, findings] = await Promise.all([
      supabase.from("assessments").select("*").eq("id", assessment_id).maybeSingle(),
      supabase.from("global_test_results").select("*").eq("assessment_id", assessment_id),
      supabase.from("segmental_test_results").select("*").eq("assessment_id", assessment_id),
      supabase.from("functional_findings").select("*").eq("assessment_id", assessment_id)
    ]);
    if (assessment.error) {
      return { content: [{ type: "text", text: assessment.error.message }], isError: true };
    }
    if (!assessment.data) {
      return { content: [{ type: "text", text: "Assessment not found." }], isError: true };
    }
    const payload = {
      assessment: assessment.data,
      global_test_results: globals.data ?? [],
      segmental_test_results: segmentals.data ?? [],
      functional_findings: findings.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-protocols.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(requireServerEnv("SUPABASE_URL"), requireServerEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_protocols_default = defineTool5({
  name: "list_protocols",
  title: "List protocols",
  description: "List exercise protocols visible to the signed-in user. Optionally filter by student or assessment.",
  inputSchema: {
    student_id: z4.string().uuid().optional(),
    assessment_id: z4.string().uuid().optional(),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ student_id, assessment_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    let q = supabase.from("protocols").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (student_id) q = q.eq("student_id", student_id);
    if (assessment_id) q = q.eq("assessment_id", assessment_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { protocols: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-progress-logs.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(requireServerEnv("SUPABASE_URL"), requireServerEnv("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_progress_logs_default = defineTool6({
  name: "list_progress_logs",
  title: "List progress logs",
  description: "List exercise progress logs for a student or protocol.",
  inputSchema: {
    student_id: z5.string().uuid().optional(),
    protocol_id: z5.string().uuid().optional(),
    limit: z5.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ student_id, protocol_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser6(ctx);
    let q = supabase.from("progress_logs").select("*").order("completed_at", { ascending: false }).limit(limit ?? 100);
    if (student_id) q = q.eq("student_id", student_id);
    if (protocol_id) q = q.eq("protocol_id", protocol_id);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { logs: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xrtsioacrybmcexyhaia";
var mcp_default = defineMcp({
  name: "fabrik-mcp",
  title: "Fabrik \u2014 Functional Assessment",
  version: "0.1.0",
  instructions: "Tools to read a physiotherapist's Fabrik data: students, functional assessments, global/segmental test results, generated protocols, and exercise progress logs. All calls are scoped to the signed-in user via row-level security. Use `whoami` to confirm identity, `list_students` and `list_assessments` to browse, and `get_assessment` for full detail including test results and findings.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_students_default,
    list_assessments_default,
    get_assessment_default,
    list_protocols_default,
    list_progress_logs_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
