-- Limpar exercícios existentes e popular com biblioteca curada FABRIK
-- Fonte: Lista_de_exercícios_FABRIK.xlsx + Rebuilding MILO + NASM CES

DELETE FROM exercises WHERE created_by IS NULL;

-- FASE 1: MOBILITY (10 exercícios)
INSERT INTO exercises (name, description, fabrik_phase, body_region, target_classifications, target_muscles, video_url, progression_criteria, is_active) VALUES
('Joelho na Parede', 'Mobilização de dorsiflexão do tornozelo em pé contra a parede', 'mobility', 'ankle', '["Dorsiflexion", "Gastroc", "Soleus"]', '["gastrocnêmio", "sóleo", "tibial anterior"]', 'https://www.youtube.com/watch?v=5eXRznLEwkg', 'Progredir para versão com elevação', true),
('Flexores do Quadril 1/2 Ajoelhado', 'Alongamento dinâmico dos flexores do quadril em posição de meio ajoelhado', 'mobility', 'hip', '["HipFlexors", "HipFlexion"]', '["iliopsoas", "reto femoral", "tensor da fáscia lata"]', 'https://www.youtube.com/watch?v=EqO5IZEtxbc', 'Adicionar rotação torácica', true),
('Couch Stretch', 'Alongamento profundo dos flexores do quadril com apoio na parede', 'mobility', 'hip', '["HipFlexors", "HipFlexion"]', '["iliopsoas", "reto femoral"]', 'https://www.youtube.com/watch?v=LV2dGjd5A9w', 'Aumentar tempo de sustentação', true),
('90/90 com Rotação', 'Mobilização de rotação interna e externa do quadril em posição 90/90', 'mobility', 'hip', '["HipER", "Piriformis"]', '["piriforme", "glúteo médio", "rotadores externos"]', 'https://www.youtube.com/watch?v=SqxDqBdWaZI', 'Adicionar inclinação do tronco', true),
('Cat/Camel', 'Mobilização segmentar da coluna em flexão e extensão', 'mobility', 'thoracic', '["TspineExtension", "LumbarControl"]', '["eretores da coluna", "reto abdominal", "multífidos"]', 'https://www.youtube.com/watch?v=K9bK0BwKFjs', 'Isolar movimento por segmento', true),
('Rotação Torácica 3 Apoios', 'Mobilização de rotação torácica em posição de 3 apoios', 'mobility', 'thoracic', '["TspineExtension", "RotationalControl"]', '["oblíquos", "multífidos", "rotadores"]', 'https://www.youtube.com/watch?v=I0K4MNXGKZ4', 'Aumentar amplitude progressivamente', true),
('Extensão Torácica no Rolo', 'Extensão torácica com foam roller', 'mobility', 'thoracic', '["TspineExtension", "Paravertebrals"]', '["eretores torácicos", "multífidos"]', 'https://www.youtube.com/watch?v=LT_dFRnmdGs', 'Progredir segmento por segmento', true),
('Deslizamento Escapular', 'Mobilização do ombro com deslizamento na parede', 'mobility', 'shoulder', '["ShoulderFlexion", "PecMinor"]', '["serrátil anterior", "trapézio inferior", "peitoral menor"]', 'https://www.youtube.com/watch?v=aWv6fE7Kqx8', 'Adicionar resistência com banda', true),
('Adutor Rock', 'Mobilização dos adutores em posição de rock', 'mobility', 'hip', '["Adductors", "HipFlexion"]', '["adutores magno", "longo", "curto"]', 'https://www.youtube.com/watch?v=XP9bLzCfep0', 'Aumentar amplitude da abertura', true),
('Melhor do Mundo com Rotação', 'Mobilização integrada de quadril e coluna torácica', 'mobility', 'hip', '["HipFlexors", "TspineExtension"]', '["iliopsoas", "oblíquos", "rotadores"]', 'https://www.youtube.com/watch?v=JxPOlBvETgc', 'Adicionar alcance do braço', true);

-- FASE 2: INHIBITION (12 exercícios)
INSERT INTO exercises (name, description, fabrik_phase, body_region, target_classifications, target_muscles, video_url, progression_criteria, is_active) VALUES
('LMF Panturrilha', 'Liberação miofascial da panturrilha com foam roller', 'inhibition', 'ankle', '["Gastroc", "Soleus", "Dorsiflexion"]', '["gastrocnêmio", "sóleo"]', 'https://www.youtube.com/watch?v=x-EHULGi3xo', 'Adicionar rotação do pé durante liberação', true),
('LMF TFL', 'Liberação miofascial do tensor da fáscia lata', 'inhibition', 'hip', '["TFL", "ITBand", "LateralPelvic"]', '["tensor da fáscia lata", "banda iliotibial"]', 'https://www.youtube.com/watch?v=eBjZWCnFzNk', 'Progredir para bola de lacrosse', true),
('LMF Adutores', 'Liberação miofascial dos adutores do quadril', 'inhibition', 'hip', '["Adductors", "FrontalPlane"]', '["adutores magno", "longo", "curto", "grácil"]', 'https://www.youtube.com/watch?v=bC-Ynv9z8J0', 'Trabalhar diferentes ângulos de rotação', true),
('LMF Glúteos', 'Liberação miofascial dos glúteos com foco no piriforme', 'inhibition', 'hip', '["Piriformis", "GluteMax"]', '["piriforme", "glúteo máximo", "glúteo médio"]', 'https://www.youtube.com/watch?v=SvXR5-DJLFo', 'Usar bola de lacrosse para maior especificidade', true),
('LMF Flexores do Quadril', 'Liberação miofascial do quadríceps e flexores do quadril', 'inhibition', 'hip', '["HipFlexors", "QuadEccentric"]', '["reto femoral", "vasto lateral", "iliopsoas"]', 'https://www.youtube.com/watch?v=RpKuTn9MLqE', 'Adicionar flexão ativa do joelho durante liberação', true),
('LMF Posteriores da Coxa', 'Liberação miofascial dos isquiotibiais', 'inhibition', 'hip', '["Hamstrings"]', '["bíceps femoral", "semitendíneo", "semimembranoso"]', 'https://www.youtube.com/watch?v=wkVf6QrBqVY', 'Progredir para liberação com extensão ativa', true),
('LMF Coluna Torácica', 'Liberação miofascial da região torácica', 'inhibition', 'thoracic', '["Paravertebrals", "TspineExtension"]', '["eretores da coluna", "romboide", "trapézio médio"]', 'https://www.youtube.com/watch?v=K-CrEi0ymMg', 'Trabalhar mobilidade segmentar', true),
('LMF Latíssimo', 'Liberação miofascial do latíssimo do dorso', 'inhibition', 'shoulder', '["Lats", "ShoulderFlexion"]', '["latíssimo do dorso"]', 'https://www.youtube.com/watch?v=4Lr6fBmb9IY', 'Adicionar movimento do braço durante liberação', true),
('LMF Peitoral', 'Liberação miofascial do peitoral com bola', 'inhibition', 'shoulder', '["PecMajor", "PecMinor"]', '["peitoral maior", "peitoral menor"]', 'https://www.youtube.com/watch?v=IHgwkNTNJN0', 'Progredir para alongamento ativo', true),
('LMF Planta do Pé', 'Liberação miofascial da fáscia plantar', 'inhibition', 'foot', '["FootIntrinsics", "Arch"]', '["fáscia plantar", "intrínsecos do pé"]', 'https://www.youtube.com/watch?v=f-DFjmOyTVE', 'Progredir para exercícios de ativação', true),
('Alongamento Bi-fásico Panturrilha', 'Alongamento estático da panturrilha em duas fases', 'inhibition', 'ankle', '["Gastroc", "Soleus"]', '["gastrocnêmio", "sóleo"]', 'https://www.youtube.com/watch?v=1radAfqhks4', 'Manter progressão de tempo', true),
('Respiração 4-7-8', 'Técnica de respiração para ativação parassimpática e inibição neural', 'inhibition', 'lumbar', '["CoreDeep"]', '["diafragma", "transverso abdominal"]', NULL, 'Aumentar ciclos progressivamente', true);

-- FASE 3: ACTIVATION (12 exercícios)
INSERT INTO exercises (name, description, fabrik_phase, body_region, target_classifications, target_muscles, video_url, progression_criteria, is_active) VALUES
('Clam Shell', 'Ativação do glúteo médio em decúbito lateral', 'activation', 'hip', '["GluteMed", "GluteMin", "LateralPelvic"]', '["glúteo médio", "glúteo mínimo"]', 'https://www.youtube.com/watch?v=cFmMG5Bvt0w', 'Adicionar mini-band', true),
('Clam Shell com Mini-Band', 'Ativação do glúteo médio com resistência', 'activation', 'hip', '["GluteMed", "LateralPelvic", "FrontalControl"]', '["glúteo médio", "glúteo mínimo"]', 'https://www.youtube.com/watch?v=aJ0IZiGEb4w', 'Aumentar resistência da banda', true),
('Ponte', 'Ativação de glúteo máximo em ponte supina', 'activation', 'hip', '["GluteMax", "LumbarControl"]', '["glúteo máximo", "isquiotibiais"]', 'https://www.youtube.com/watch?v=8bbE64NuDTU', 'Progredir para ponte unilateral', true),
('Ponte Unilateral', 'Ativação avançada de glúteo em apoio unilateral', 'activation', 'hip', '["GluteMax", "GluteMed", "LateralPelvic"]', '["glúteo máximo", "glúteo médio"]', 'https://www.youtube.com/watch?v=AVAXhy6pl7o', 'Adicionar elevação de calcâneo', true),
('Cobra (Prone Y)', 'Ativação de trapézio inferior em decúbito ventral', 'activation', 'shoulder', '["TrapInf", "TrapMid", "Scapula"]', '["trapézio inferior", "trapézio médio"]', 'https://www.youtube.com/watch?v=K_pS_b4hy3U', 'Adicionar carga leve', true),
('Y em Decúbito Ventral', 'Ativação isolada do trapézio inferior', 'activation', 'shoulder', '["TrapInf", "Scapula", "ScapularRhythm"]', '["trapézio inferior", "serrátil anterior"]', 'https://www.youtube.com/watch?v=fYO0X4mZz2g', 'Progredir para posição inclinada', true),
('W em Decúbito Ventral', 'Ativação de rotadores externos e trapézio médio', 'activation', 'shoulder', '["TrapMid", "Rhomboids", "ShoulderER"]', '["trapézio médio", "romboides", "infraespinhal"]', 'https://www.youtube.com/watch?v=1GrhWMJQNn8', 'Adicionar resistência com banda', true),
('4 Apoios com Extensão de Quadril', 'Ativação de glúteo máximo em posição quadrúpede', 'activation', 'hip', '["GluteMax", "GluteMed", "Core"]', '["glúteo máximo", "glúteo médio", "core"]', 'https://www.youtube.com/watch?v=6ANlvwwBmek', 'Progredir para perdigueiro', true),
('Dead Bug', 'Ativação de core profundo com dissociação de membros', 'activation', 'lumbar', '["CoreDeep", "LumbarControl", "Core"]', '["transverso abdominal", "oblíquos", "multífidos"]', 'https://www.youtube.com/watch?v=g_BYB0R-4Ws', 'Adicionar resistência com banda ou kettlebell', true),
('Prancha Lateral de Joelhos', 'Ativação de core lateral em posição modificada', 'activation', 'lumbar', '["CoreLateral", "GluteMed"]', '["oblíquos", "quadrado lombar", "glúteo médio"]', 'https://www.youtube.com/watch?v=0yKShEHB65E', 'Progredir para prancha lateral completa', true),
('Troca de Pegada com Kettlebell', 'Ativação de intrínsecos do pé com transferência de peso', 'activation', 'foot', '["FootIntrinsics", "Arch", "Ankle"]', '["intrínsecos do pé", "tibial posterior"]', 'https://www.youtube.com/watch?v=DFOIW9AJBX0', 'Aumentar carga do kettlebell', true),
('Flexão Plantar com Ênfase Fibulares', 'Ativação dos fibulares com swiss ball', 'activation', 'ankle', '["Peroneals", "Ankle"]', '["fibular longo", "fibular curto"]', NULL, 'Progredir para versão unilateral', true);

-- FASE 4: STABILITY (12 exercícios)
INSERT INTO exercises (name, description, fabrik_phase, body_region, target_classifications, target_muscles, video_url, progression_criteria, is_active) VALUES
('Prancha Baixa', 'Estabilização isométrica de core em posição de prancha', 'stability', 'lumbar', '["Core", "LumbarControl", "CoreDeep"]', '["reto abdominal", "transverso", "eretores"]', 'https://www.youtube.com/watch?v=ASdvN_XEl_c', 'Progredir para variações dinâmicas', true),
('Prancha Lateral', 'Estabilização lateral do core', 'stability', 'lumbar', '["CoreLateral", "LateralPelvic", "GluteMed"]', '["oblíquos", "quadrado lombar", "glúteo médio"]', 'https://www.youtube.com/watch?v=K2VljzCC16g', 'Adicionar elevação de perna', true),
('Prancha Lateral com Abdução', 'Estabilização lateral com ativação de glúteo médio', 'stability', 'hip', '["GluteMed", "CoreLateral", "LateralPelvic"]', '["glúteo médio", "oblíquos", "quadrado lombar"]', 'https://www.youtube.com/watch?v=3_qP3vu6wDo', 'Adicionar mini-band', true),
('Bear Hold', 'Estabilização de core em posição quadrúpede elevada', 'stability', 'lumbar', '["Core", "CoreDeep", "LumbarControl"]', '["transverso abdominal", "reto abdominal", "serrátil"]', 'https://www.youtube.com/watch?v=4psrgMltXnQ', 'Progredir para bear crawl', true),
('Perdigueiro (Bird-Dog)', 'Estabilização com extensão de membros opostos', 'stability', 'lumbar', '["Core", "LumbarControl", "RotationalControl"]', '["multífidos", "glúteo máximo", "core"]', 'https://www.youtube.com/watch?v=wiFNA3sqjCA', 'Adicionar resistência com banda', true),
('Pallof Press', 'Estabilização anti-rotacional com resistência', 'stability', 'lumbar', '["Core", "RotationalControl", "Obliques"]', '["oblíquos", "transverso abdominal", "multífidos"]', 'https://www.youtube.com/watch?v=AH_QZLm_0-s', 'Aumentar resistência ou adicionar instabilidade', true),
('Monster Walk', 'Caminhada lateral com mini-band para estabilidade de quadril', 'stability', 'hip', '["GluteMed", "LateralPelvic", "FrontalControl"]', '["glúteo médio", "glúteo mínimo", "tensor da fáscia lata"]', 'https://www.youtube.com/watch?v=068LBaaNQb0', 'Aumentar resistência da banda', true),
('Single-Leg Deadlift (SLDL)', 'Levantamento terra unilateral para estabilidade de quadril', 'stability', 'hip', '["GluteMax", "GluteMed", "Proprioception", "LateralPelvic"]', '["glúteo máximo", "glúteo médio", "isquiotibiais"]', 'https://www.youtube.com/watch?v=Oj3LHCsU0b4', 'Adicionar carga externa', true),
('Airplane', 'Estabilização unipodal com rotação de tronco', 'stability', 'hip', '["GluteMed", "LateralPelvic", "Proprioception"]', '["glúteo médio", "glúteo máximo", "core"]', 'https://www.youtube.com/watch?v=Qrv8dSvD2E0', 'Adicionar perturbação externa', true),
('Push-up Plus (Flexão Escapular)', 'Protração escapular para ativação de serrátil anterior', 'stability', 'shoulder', '["Serratus", "Scapula", "ScapularRhythm"]', '["serrátil anterior", "peitoral"]', 'https://www.youtube.com/watch?v=xYS5B6kfqJg', 'Progredir para prancha alta com alcance', true),
('Prancha Alta com Alcance', 'Estabilização anti-rotacional com alcance unilateral', 'stability', 'shoulder', '["Core", "Scapula", "RotationalControl"]', '["core", "serrátil anterior", "deltóide"]', 'https://www.youtube.com/watch?v=0aGFVSMwKPQ', 'Adicionar objeto para tocar', true),
('Y Teste em Pé', 'Teste e treino de estabilidade com alcances em Y', 'stability', 'ankle', '["TrapInf", "Proprioception", "Ankle"]', '["trapézio inferior", "estabilizadores do tornozelo"]', 'https://www.youtube.com/watch?v=HFaXYS6WN80', 'Aumentar amplitude dos alcances', true);

-- FASE 5: STRENGTH (12 exercícios)
INSERT INTO exercises (name, description, fabrik_phase, body_region, target_classifications, target_muscles, video_url, progression_criteria, is_active) VALUES
('Agachamento Taça', 'Agachamento com carga frontal (goblet squat)', 'strength', 'hip', '["GluteMax", "VMO", "Core", "Dorsiflexion"]', '["glúteo máximo", "quadríceps", "core"]', 'https://www.youtube.com/watch?v=PKmrXTx6jZs', 'Aumentar carga ou progredir para back squat', true),
('RDL (Romanian Deadlift)', 'Levantamento terra romeno bilateral', 'strength', 'hip', '["GluteMax", "Hamstrings", "LumbarControl"]', '["glúteo máximo", "isquiotibiais", "eretores"]', 'https://www.youtube.com/watch?v=XBZvaP0Yd48', 'Aumentar carga progressivamente', true),
('Hip Thrust', 'Extensão de quadril com apoio dorsal', 'strength', 'hip', '["GluteMax", "GluteMed", "Core"]', '["glúteo máximo", "glúteo médio", "isquiotibiais"]', 'https://www.youtube.com/watch?v=xDmFkJxPzeM', 'Aumentar carga ou progredir para unilateral', true),
('Deadlift Unilateral', 'Levantamento terra unilateral com kettlebell', 'strength', 'hip', '["GluteMax", "GluteMed", "LateralPelvic"]', '["glúteo máximo", "glúteo médio", "isquiotibiais"]', 'https://www.youtube.com/watch?v=XBMrCyR9BRk', 'Aumentar carga ou adicionar rotação', true),
('Lunge Reverso', 'Avanço reverso com ou sem carga', 'strength', 'hip', '["GluteMax", "VMO", "FrontalPlane"]', '["glúteo máximo", "quadríceps", "isquiotibiais"]', 'https://www.youtube.com/watch?v=xrPteyQLGAo', 'Adicionar carga ou deficit', true),
('Step Up', 'Subida em caixa com ênfase em glúteo', 'strength', 'hip', '["GluteMax", "GluteMed", "VMO"]', '["glúteo máximo", "glúteo médio", "quadríceps"]', 'https://www.youtube.com/watch?v=dQqApCGd5Ss', 'Aumentar altura da caixa ou carga', true),
('Flexão Nórdica', 'Exercício excêntrico para isquiotibiais', 'strength', 'knee', '["Hamstrings", "QuadEccentric"]', '["isquiotibiais"]', 'https://www.youtube.com/watch?v=Rl_t7arDleY', 'Aumentar amplitude progressivamente', true),
('Remada Fechada nas Argolas', 'Remada horizontal em suspensão', 'strength', 'shoulder', '["TrapMid", "Rhomboids", "Scapula"]', '["trapézio médio", "romboides", "latíssimo"]', 'https://www.youtube.com/watch?v=Ef7z7DREC-s', 'Aumentar inclinação ou adicionar pausa', true),
('Face Pull', 'Puxada para o rosto com rotação externa', 'strength', 'shoulder', '["TrapMid", "TrapInf", "ShoulderER", "Scapula"]', '["trapézio médio", "trapézio inferior", "deltóide posterior"]', 'https://www.youtube.com/watch?v=rep-qVOkqgk', 'Aumentar carga mantendo qualidade', true),
('Flexão de Braços', 'Push-up tradicional com ênfase em protração', 'strength', 'shoulder', '["Serratus", "Core", "PecMajor"]', '["peitoral maior", "tríceps", "serrátil anterior"]', 'https://www.youtube.com/watch?v=IODxDxX7oi4', 'Progredir para variações avançadas', true),
('Press Landmine 1/2 Ajoelhado', 'Press com landmine em posição de meio ajoelhado', 'strength', 'shoulder', '["Serratus", "Core", "ShoulderFlexion"]', '["serrátil anterior", "deltóide anterior", "core"]', 'https://www.youtube.com/watch?v=Oy4DeDvYpQg', 'Aumentar carga ou adicionar rotação', true),
('Agachamento Unilateral', 'Agachamento pistol ou búlgaro', 'strength', 'hip', '["GluteMax", "VMO", "LateralPelvic", "Proprioception"]', '["glúteo máximo", "quadríceps", "estabilizadores"]', 'https://www.youtube.com/watch?v=vq5-vdgJc0I', 'Aumentar carga ou amplitude', true);

-- FASE 6: INTEGRATION (10 exercícios)
INSERT INTO exercises (name, description, fabrik_phase, body_region, target_classifications, target_muscles, video_url, progression_criteria, is_active) VALUES
('Agachamento Overhead', 'Agachamento com braços elevados', 'integration', 'full_body', '["Core", "ShoulderFlexion", "Dorsiflexion", "GlobalMotorControl"]', '["core", "deltóides", "glúteos", "quadríceps"]', 'https://www.youtube.com/watch?v=RD_vUnqwqqI', 'Adicionar carga com bastão ou barra', true),
('Windmill', 'Moinho de vento com kettlebell', 'integration', 'full_body', '["Core", "RotationalControl", "ShoulderFlexion", "GluteMed"]', '["oblíquos", "glúteos", "estabilizadores do ombro"]', 'https://www.youtube.com/watch?v=kbGIxmYLdgs', 'Aumentar carga ou adicionar KB inferior', true),
('Lunge Matrix', 'Avanços em múltiplas direções', 'integration', 'full_body', '["GluteMed", "GluteMax", "RotationalControl", "GlobalMotorControl"]', '["glúteos", "quadríceps", "adutores", "core"]', 'https://www.youtube.com/watch?v=HGwpXzLH5M0', 'Adicionar carga ou velocidade', true),
('Bear Crawl', 'Caminhada de urso para integração de padrões', 'integration', 'full_body', '["Core", "Scapula", "RotationalControl", "GlobalMotorControl"]', '["core", "serrátil", "deltóides", "glúteos"]', 'https://www.youtube.com/watch?v=N1qGLgDLHiA', 'Aumentar distância ou adicionar carga', true),
('Kettlebell Swing', 'Balanço de kettlebell com extensão de quadril', 'integration', 'full_body', '["GluteMax", "Core", "LumbarControl"]', '["glúteo máximo", "isquiotibiais", "core"]', 'https://www.youtube.com/watch?v=YSxHifyI6s8', 'Aumentar carga ou progredir para clean', true),
('Clean to Box', 'Clean com kettlebell para a caixa', 'integration', 'full_body', '["GluteMax", "Core", "GlobalMotorControl"]', '["glúteo máximo", "quadríceps", "trapézio", "core"]', 'https://www.youtube.com/watch?v=4fH5dNiWXyI', 'Aumentar altura da caixa ou carga', true),
('Turkish Get-Up (Flow 1)', 'Levantamento turco - primeira metade', 'integration', 'full_body', '["Core", "Scapula", "GluteMax", "GlobalMotorControl"]', '["core", "glúteos", "ombro", "quadríceps"]', 'https://www.youtube.com/watch?v=0bWRPC6g8N0', 'Progredir para TGU completo', true),
('Burpee', 'Burpee para condicionamento e integração', 'integration', 'full_body', '["Core", "GlobalMotorControl"]', '["peitoral", "core", "quadríceps", "glúteos"]', 'https://www.youtube.com/watch?v=TU8QYVW0gDU', 'Adicionar variações (pull-up, box jump)', true),
('Box Jump', 'Salto na caixa para potência', 'integration', 'full_body', '["GluteMax", "QuadEccentric", "Proprioception"]', '["glúteo máximo", "quadríceps", "panturrilha"]', 'https://www.youtube.com/watch?v=hxldG9FX4j4', 'Aumentar altura da caixa', true),
('Arremesso Overhead com Passada', 'Arremesso de medicine ball com rotação', 'integration', 'full_body', '["Core", "RotationalControl", "GlobalMotorControl"]', '["oblíquos", "deltóides", "core", "glúteos"]', 'https://www.youtube.com/watch?v=1Y4Z0h0Vjug', 'Aumentar peso da bola ou velocidade', true);